name: Library Management CI

on:
    push: 
        branches: [ main ]
    pull_request: 

jobs:
    run-tests:
        strategy: 
            fail-fast: false
            matrix: 
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version:
                    - "3.8"
                    - "3.9"
                    - "3.10"
                    - "3.11"
                    - "3.12-dev"

        name: Test
        runs-on: ${{ matrix.os }}

        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Set up Python
            uses: actions/setup-python@v5
            with: 
                python-version: ${{ matrix.python-version }}

          - name: Install dependencies
            shell: bash
            run: |
                python -m pip install --upgrade pip
                python -m pip install pytest 
                pip install -r requirements.txt pytest-mock
                pip install --force-reinstall pytest pytest-mock
                pip install pytest-playwright
                playwright install
                pip install pytest-playwright playwright -U

          - name: Verify pytest-mock installation
            shell: bash
            run: |
              python -m pip list
              echo "---- pytest-mock package info ----"
              python -m pip show pytest-mock || echo "pytest-mock not installed!"
              echo "---- pytest version ----"
              python -m pytest --version

          - name: Run Flask 
            run: |
              python app.py & 
              echo $! > flask.pid
              sleep 10
            shell: bash

          - name: Wait For Flask to Load (to run tests on MacOS)
            run: |
              echo "Waiting for Flask to load..."
              for i in {1..10}; do 
                if curl -f http://127.0.0.1:5000/ 2>/dev/null; then
                  echo "Flask is ready."
                  break
                fi
                sleep 1
                if [ $i -eq 120 ]; then
                  echo "Flask failed to start within 2 minutes."
                  cat flask.log || true
                  exit 1
                fi
              done
            shell: bash
            
          - name: Run tests
            shell: bash
            run: python -m pytest -v

          - name: Stop Flask app
            if: always()
            run: |
              if [ -f flask.pid ]; then
                kill $(cat flask.pid) || true
              fi
            shell: bash


            